# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171220_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='docfile',
            field=models.FileField(default='MEDIA_ROOT/bali-secret-beach.jpg', upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Blog title', max_length=200),
        ),
    ]
