# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171220_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='docfile',
            field=models.FileField(default=None, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
