# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171221_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='h1text',
        ),
        migrations.AddField(
            model_name='post',
            name='h1',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='h1date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='h1image',
            field=models.FileField(blank=True, default=None, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
