# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171221_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='h1text',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.TextField(blank=True, default=None),
        ),
    ]
