# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171221_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, default=None, max_length=300),
        ),
    ]
