# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20171221_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='h1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
