# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_post_h1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='h1date',
        ),
        migrations.AddField(
            model_name='post',
            name='h1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
