# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20171221_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='h1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='h1text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
