# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20171221_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='h1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='h1image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='h1text',
        ),
    ]
