# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20171221_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='h1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='h1image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='h1text',
            field=models.TextField(null=True),
        ),
    ]
