# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_post_h1date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='h1date',
            field=models.DateField(null=True),
        ),
    ]
