# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20171221_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='h1date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
