# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20171221_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='h1date',
            new_name='First_paragraph_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='h1image',
            new_name='First_paragraph_image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='h1text',
            new_name='First_paragraph_text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='h1',
            new_name='First_paragraph_title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='intro',
            new_name='Introduction_text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='subtitle',
            new_name='Subtitle',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='docfile',
            new_name='Title_image',
        ),
    ]
