# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 13:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20171221_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Second_paragraph_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='post',
            name='Second_paragraph_image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='Second_paragraph_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Second_paragraph_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
