# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20171221_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='First_paragraph_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Second_paragraph_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
